parameters:
- name: Version
  type: string
  default: ''
- name: OriginalBuildId
  displayName: Original Build Id
  type: string
  default: ''
  
trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

extends:
  template: /eng/pipelines/templates/just-release.yml
  parameters:
    OriginalBuildId: ${{ parameters.OriginalBuildId }}
    Version: ${{ parameters.Version }}